# Generated by Django 4.0.1 on 2022-05-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('1', 'High'), ('1', 'Medium'), ('1', 'Low')], max_length=10)),
                ('isCompleted', models.BooleanField()),
                ('updated_date', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
